# Generated by Django 5.0.6 on 2024-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pagocomun_usuario_alter_pagocomun_num_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocomun',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
