# Generated by Django 5.0.6 on 2024-12-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pagocomun_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocomun',
            name='fecha_pago',
        ),
    ]
